### ISSUE TITLE
Add user problem

### ISSUE THREAD

**Issue by dnievas8k** [ppetrid/yawd-admin#18] opened 2013-10-02 14:44 UTC
We are working with yawd-admin v0.7.0 and django-1.5.2. When we try to add a new user, we see the edition form instead of the add form. Another problem we found is that the password input in the html is not of type password as it should be. More on this, is that when we try to save the changes, the password is not encrypted.

**Comment by ghost** [comment] 2013-10-21 14:48
Hello, sorry for the late reaction, but I am not able to reproduce this problem with the current master. Can you please give some more information? (e.g. did you use custom user models etc)??As far as the password input is concerned, which form/page are you referring to? Pasword inputs are used in various yawd-admin templates (e.g. login screen, change user, add user, "my account" view, password reset and so on)

**Comment by Nabu-thinker-ru** [comment] 2013-10-22 09:34
I didnt see this too. On my custom user model all is looking fine.

**Comment by ghost** [comment] 2013-10-22 13:02
Ok, so let's close this for now and see if someone objects :)

**Closed as completed** 2013-10-22 13:02 UTC

**Comment by WillowireDave** [comment] 2014-06-23 22:22
I'm having a similar issue, build is Django 1.5 with Yawd-admin 1.7.  No custom user models are being used.  When a password is set through the admin interface it is stored unhashed in the db, but creating a user from the command line or within the website functions properly.
![password_unhashed](https://cloud.githubusercontent.com/assets/4175408/3364842/c8474b54-fb24-11e3-9360-8d924af3fe61.png)
